### ISSUE TITLE
Example project callbacks not working

### ISSUE THREAD

**Issue by KMIxx** [cleverpush/cleverpush-flutter-sdk#7]
Hello

I'm trying to get the example project working on Android but it seems there are no callbacks coming from the library side.
The subscription ID appears in the Cleverpush console `https://app.cleverpush.com/`. The test push notifications sent from the console are not received one the phone.

`flutter --version`:
```
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (5 weeks ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
```

Logs:
```
I/flutter (18783): CleverPush: Flutter initializing
D/CleverPush(18783): Initializing with Channel ID: iw7........s42G (SDK 1.14.5)
D/SharedPreferencesImpl(18783): Time required to fsync /data/user/0/com.cleverpush.example/shared_prefs/com.cleverpush.example_preferences.xml: [<1: 0, <2: 0, <4: 0, <8: 0, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 1, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
I/FirebaseCrash(18783): Sending crashes
I/zygote64(18783): Do partial code cache collection, code=30KB, data=23KB
I/zygote64(18783): After code cache collection, code=30KB, data=28KB
I/zygote64(18783): Increasing code cache capacity to 128KB
D/CleverPush(18783): Subscribed with ID (next sync at 2021-06-24 10:37:37 EEST): uD..........niiF
I/flutter (18783): CleverPush: _handleMethod: CleverPush#handleSubscribed
I/flutter (18783): _InternalLinkedHashMap<Object?, Object?>
```

Example: https://github.com/cleverpush/cleverpush-flutter-sdk/tree/master/example

I debugged the `CleverPush` class inside  `cleverpush_flutter.dart` 
The MethodCall method name seems to be correct and is valid in the if/else block but nothing is received in the callback
Screenshot: https://www.dropbox.com/s/6oqufq1hmpfrhmm/Screenshot%202021-06-21%20at%2010.40.58.png?dl=0

The init is the same as in the example project, just added some extra log lines but they are not invoked:
```
  Future<void> initPlatformState() async {
    if (!mounted) return;

    CleverPush.shared.setNotificationReceivedHandler((CPNotificationReceivedResult result) {
      print('TEST - received');
      this.setState(() {
        _debugLabelString = "Notification received: \n${result.notification.jsonRepresentation().replaceAll("\\n", "\n")}";
      });
    });

    CleverPush.shared.setNotificationOpenedHandler((CPNotificationOpenedResult result) {
      print('TEST - opened');
      this.setState(() {
        _debugLabelString = "Notification opened: \n${result.notification.jsonRepresentation().replaceAll("\\n", "\n")}";
      });
    });

    CleverPush.shared.setSubscribedHandler((subscriptionId) {
      print('TEST - SUBSCRIBED');
      this.setState(() {
        _debugLabelString = "Subscribed: " + subscriptionId;
      });

      print("Subscribed: ${subscriptionId}");
    });

    // CleverPush Channel ID
    await CleverPush.shared.init("iw7............42G", true);
  }
```

**Comment by gbhrdt** [comment]
Hi @KMIxx  thanks for your message! We were able to run the example project without any issue with these changes/updates needed to run with the latest Android Studio and Firebase versions:

1. upgrade version
```
classpath 'com.android.tools.build:gradle:4.1.0 '
```
2. comment out code of crashlytics
3. upgrade this:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
```

If that does not help: Could you maybe share your `pubspec.yaml` file? 
And are you maybe still initializing Firebase Messaging in your Flutter code somewhere? I would try to remove/comment this.

**Comment by KMIxx** [comment]
Thanks for the feedback! I made another test with the suggested changes but still no change (no logs in the callbacks and the "_debugLabelString" variable is not updated when device is subscribed).

I extracted the example project and in the dependencies section pointed to use the "cleverpush_flutter: ^1.5.4"
You can try the same project I have from here, i compressed it to a zip file: https://www.dropbox.com/s/zsr02u5zrf1vhgx/example.zip?dl=0

There was a problem that I get a warning that SDK constraint is not defined so I added
```
environment:
  sdk: '>=2.10.0 <3.0.0'
```

I also had to remove Fabric  SDK because that project is dead (reference: https://firebase.google.com/docs/crashlytics/upgrade-sdk) and in the console i was getting this error:
```
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kmi/Downloads/cleverpush-flutter-sdk-master/example/android/build.gradle' line: 34

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > groovy.lang.MissingPropertyException: No such property: scope for class: com.android.build.gradle.internal.variant.ApplicationVariantData

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1
```

I did not dive in to Firebase related dependency clashes yet so I commented the Firebase Android dependencies out (Android project level build.gradle file):
```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
//    implementation "com.google.firebase:firebase-crash:+"
    implementation 'com.yieldlove.adIntegration:yieldlove:5.1.0'
}
```

The error I'm getting when Firebase is not commented out:
```
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.gms.internal.firebase_messaging.zza found in modules jetified-firebase-iid-17.0.3-runtime (com.google.firebase:firebase-iid:17.0.3) and jetified-firebase-messaging-22.0.0-runtime (com.google.firebase:firebase-messaging:22.0.0)
... (more similar lines)
```

My pubspec.yaml:
```
name: cleverpush_example
description: Demonstrates how to use the cleverpush plugin.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+6
  cleverpush_flutter: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

I also updated my environment, i'm now running on:
```
Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 10, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, andrasferenczi.dart-data-plugin, com.localizely.flutter-intl, org.jetbrains.kotlin, io.flutter
```
Flutter/Dart:
```
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (2 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

**Comment by gbhrdt** [comment]
Hi @KMIxx thanks for the detailed explanation! We have indeed been able to identify an issue with the Subscribed Handler. All other Handlers (Notification Opened / Received) were working for us without any issues in the example project.

We have now released version 1.6.0 which should fix the Subscribed handler. The example project has also been upgraded in various ways and should now work without any further changes needed :-).
Thanks again for your great support on this.

**Comment by KMIxx** [comment]
Seems to be working, thank you!

**Comment by KMIxx** [comment]
Hello again, seems that there is still a problem when running the example in release mode with "--release" argument.

In order to see the the problem one should not build the app in the release mode when it's already installed in debug mode, - when installing first in debug mode then things seem to be working, might be some caching issue (perhaps the subscriptionID is cached in the library side and then returned immediately in release mode).  

Steps to reproduce:
1) Uninstall existing example app
2) In the Android Studio run configuration add "--release" argument and then run the project or from command line run "flutter run --release" 

In the release mode the subscription ID is never returned in the callback.

When running in release mode ("flutter run --release") then in the logs it says that it's initializing and nothing else:
```
I/flutter (30415): CleverPush: Flutter initializing
```

When running in debug mode with "flutter run --debug" then this is the output:
```
I/flutter (31131): CleverPush: Flutter initializing
D/CleverPush(31131): Initializing with Channel ID: hxWyS7jPk4DrnSk5K (SDK 1.14.5)
I/zygote64(31131): Do partial code cache collection, code=30KB, data=23KB
I/zygote64(31131): After code cache collection, code=30KB, data=23KB
I/zygote64(31131): Increasing code cache capacity to 128KB
I/CleverPush(31131): Device registered (FCM), push token: czf0HfUkTdmtX0rAkjEho_:APA91bHrOyEzWTjstJBxb3KBq6Q2vVgcxfEeKPomhlsSIZJUb3clV8j70-bg4A9fVsv1yt01VRX0LOx8Ct7aPCHBwS7FZIIwELdkM5qIpYmrOyHrTWXilvh_5Pe-KtGRQXvb17w24lkB
D/CleverPush(31131): syncSubscription
The Flutter DevTools debugger and profiler on Nexus 6P is available at:
http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A51264%2FK20M1_L5XcI%3D%2F
D/CleverPush(31131): sync response: {"id":"wkeXYZKWw6vkT7zcK","topics":["Wdj8TArZi5PsruyxC","tabEhawqMfDsvscLn"]}
D/CleverPush(31131): subscribed with ID: wkeXYZKWw6vkT7zcK
D/CleverPush(31131): Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
D/CleverPush(31131): setSubscriptionTopics: [Wdj8TArZi5PsruyxC, tabEhawqMfDsvscLn]
I/flutter (31131): Subscribed: wkeXYZKWw6vkT7zcK

```

**Comment by gbhrdt** [comment]
Hi @KMIxx  are you maybe using ProGuard?

If yes - could you try to add these Exceptions to your ProGuard file?

```
-keep class com.cleverpush.** { *; }
-keep interface com.cleverpush.** { *; }
```

**Comment by KMIxx** [comment]
Hey

I'm using the example project as a reference point, i downloaded the new example which was updated a few days ago. It does not have minification enabled. 

Even when i enable minification then the result is the same:

App level build.gradle
```
...
buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
...
```

proguard-rules.pro:
```
-keep class com.cleverpush.** { *; }
-keep interface com.cleverpush.** { *; }
```

**Comment by gbhrdt** [comment]
Hi @KMIxx  

thanks, then we can exclude ProGuard which is great.

I just did another test:

```
flutter run -- release
```

works perfectly for me:

```
 % flutter run --release                                                                                                                             (git)-[master] 
Launching lib/main.dart on HRY LX1 in release mode...
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      24,9s
✓ Built build/app/outputs/apk/release/app-release.apk (7.5MB).
Installing build/app/outputs/apk/app.apk...                         1,1s
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /Users/******/******/cleverpush-flutter-sdk/example/build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.cleverpush.example signatures do not
match previously installed version; ignoring!]
Uninstalling old version...
Installing build/app/outputs/apk/app.apk...                         2,4s

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (30022): CleverPush: Flutter initializing
I/flutter (30022): Subscribed: c5R5vZZ6***********
```

I would suggest let's do a quick call to resolve it.

**Comment by KMIxx** [comment]
Hey @gbhrdt !

I see from those logs that you had an app previously installed as it says that it failed to update. Then uninstalled it and reinstalled it again.

The question mark in that case is that how did adb reinstall the app. I have not checked how it works under the hood, it might use the "-r" flag to keep the existing data.
Reference: https://stackoverflow.com/questions/12483720/adb-how-to-reinstall-an-app-without-retaining-the-data

I can still replicate this 100%, steps:
1. Download the latest example project
2. Uninstall the example app prom your device
3. Run the example project with "--release" argument

I'm up for a call, maybe we can solve this with 2 heads :)

**Comment by gbhrdt** [comment]
Closing, as the issue has been resolved :-)
